# Railway utilise Dockerfile, ce fichier n'est pas utilisé
# Si Railway ne détecte pas Dockerfile, décommentez les lignes ci-dessous :
#
# [phases.setup]
# nixPkgs = ["maven", "jdk17"]
#
# [phases.build]
# cmds = ["mvn clean package -DskipTests"]
#
# [start]
# cmd = "java -jar app.jar"

